on:
  repository_dispatch:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_EMAIL: action@github.com
  GIT_AUTHOR_NAME: actions-user
  GIT_COMMITTER_EMAIL: action@github.com
  GIT_COMMITTER_NAME: actions-user
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Update version
        run: npm i @spyglassmc/language-server@latest --package-lock-only --save-exact
        working-directory: language-server

      - name: Commit
        run: |
          git add .
          git commit -m "⬆️ Update @spyglassmc/language-server"
          git push
